# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hfl/edu/guoy_phase/mathematica

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hfl/edu/guoy_phase/mathematica

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hfl/edu/guoy_phase/mathematica/CMakeFiles /home/hfl/edu/guoy_phase/mathematica//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hfl/edu/guoy_phase/mathematica/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ueye_link

# Build rule for target.
ueye_link: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ueye_link
.PHONY : ueye_link

# fast build rule for target.
ueye_link/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/build
.PHONY : ueye_link/fast

#=============================================================================
# Target rules for targets named test_wstp

# Build rule for target.
test_wstp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_wstp
.PHONY : test_wstp

# fast build rule for target.
test_wstp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/build
.PHONY : test_wstp/fast

#=============================================================================
# Target rules for targets named ueye_link_autogen

# Build rule for target.
ueye_link_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ueye_link_autogen
.PHONY : ueye_link_autogen

# fast build rule for target.
ueye_link_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link_autogen.dir/build.make CMakeFiles/ueye_link_autogen.dir/build
.PHONY : ueye_link_autogen/fast

#=============================================================================
# Target rules for targets named test_wstp_autogen

# Build rule for target.
test_wstp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_wstp_autogen
.PHONY : test_wstp_autogen

# fast build rule for target.
test_wstp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp_autogen.dir/build.make CMakeFiles/test_wstp_autogen.dir/build
.PHONY : test_wstp_autogen/fast

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

Display.o: Display.cpp.o
.PHONY : Display.o

# target to build an object file
Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Display.cpp.o
.PHONY : Display.cpp.o

Display.i: Display.cpp.i
.PHONY : Display.i

# target to preprocess a source file
Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Display.cpp.i
.PHONY : Display.cpp.i

Display.s: Display.cpp.s
.PHONY : Display.s

# target to generate assembly for a file
Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Display.cpp.s
.PHONY : Display.cpp.s

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

MathematicaL.o: MathematicaL.cpp.o
.PHONY : MathematicaL.o

# target to build an object file
MathematicaL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MathematicaL.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/MathematicaL.cpp.o
.PHONY : MathematicaL.cpp.o

MathematicaL.i: MathematicaL.cpp.i
.PHONY : MathematicaL.i

# target to preprocess a source file
MathematicaL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MathematicaL.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/MathematicaL.cpp.i
.PHONY : MathematicaL.cpp.i

MathematicaL.s: MathematicaL.cpp.s
.PHONY : MathematicaL.s

# target to generate assembly for a file
MathematicaL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/MathematicaL.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/MathematicaL.cpp.s
.PHONY : MathematicaL.cpp.s

Worker.o: Worker.cpp.o
.PHONY : Worker.o

# target to build an object file
Worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Worker.cpp.o
.PHONY : Worker.cpp.o

Worker.i: Worker.cpp.i
.PHONY : Worker.i

# target to preprocess a source file
Worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Worker.cpp.i
.PHONY : Worker.cpp.i

Worker.s: Worker.cpp.s
.PHONY : Worker.s

# target to generate assembly for a file
Worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/Worker.cpp.s
.PHONY : Worker.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/main.cpp.s
.PHONY : main.cpp.s

test_wstp.o: test_wstp.cpp.o
.PHONY : test_wstp.o

# target to build an object file
test_wstp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp.cpp.o
.PHONY : test_wstp.cpp.o

test_wstp.i: test_wstp.cpp.i
.PHONY : test_wstp.i

# target to preprocess a source file
test_wstp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp.cpp.i
.PHONY : test_wstp.cpp.i

test_wstp.s: test_wstp.cpp.s
.PHONY : test_wstp.s

# target to generate assembly for a file
test_wstp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp.cpp.s
.PHONY : test_wstp.cpp.s

test_wstp_autogen/mocs_compilation.o: test_wstp_autogen/mocs_compilation.cpp.o
.PHONY : test_wstp_autogen/mocs_compilation.o

# target to build an object file
test_wstp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp_autogen/mocs_compilation.cpp.o
.PHONY : test_wstp_autogen/mocs_compilation.cpp.o

test_wstp_autogen/mocs_compilation.i: test_wstp_autogen/mocs_compilation.cpp.i
.PHONY : test_wstp_autogen/mocs_compilation.i

# target to preprocess a source file
test_wstp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp_autogen/mocs_compilation.cpp.i
.PHONY : test_wstp_autogen/mocs_compilation.cpp.i

test_wstp_autogen/mocs_compilation.s: test_wstp_autogen/mocs_compilation.cpp.s
.PHONY : test_wstp_autogen/mocs_compilation.s

# target to generate assembly for a file
test_wstp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_wstp.dir/build.make CMakeFiles/test_wstp.dir/test_wstp_autogen/mocs_compilation.cpp.s
.PHONY : test_wstp_autogen/mocs_compilation.cpp.s

ueye_link_autogen/mocs_compilation.o: ueye_link_autogen/mocs_compilation.cpp.o
.PHONY : ueye_link_autogen/mocs_compilation.o

# target to build an object file
ueye_link_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/ueye_link_autogen/mocs_compilation.cpp.o
.PHONY : ueye_link_autogen/mocs_compilation.cpp.o

ueye_link_autogen/mocs_compilation.i: ueye_link_autogen/mocs_compilation.cpp.i
.PHONY : ueye_link_autogen/mocs_compilation.i

# target to preprocess a source file
ueye_link_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/ueye_link_autogen/mocs_compilation.cpp.i
.PHONY : ueye_link_autogen/mocs_compilation.cpp.i

ueye_link_autogen/mocs_compilation.s: ueye_link_autogen/mocs_compilation.cpp.s
.PHONY : ueye_link_autogen/mocs_compilation.s

# target to generate assembly for a file
ueye_link_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueye_link.dir/build.make CMakeFiles/ueye_link.dir/ueye_link_autogen/mocs_compilation.cpp.s
.PHONY : ueye_link_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_wstp_autogen"
	@echo "... ueye_link_autogen"
	@echo "... test_wstp"
	@echo "... ueye_link"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... Display.o"
	@echo "... Display.i"
	@echo "... Display.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... MathematicaL.o"
	@echo "... MathematicaL.i"
	@echo "... MathematicaL.s"
	@echo "... Worker.o"
	@echo "... Worker.i"
	@echo "... Worker.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_wstp.o"
	@echo "... test_wstp.i"
	@echo "... test_wstp.s"
	@echo "... test_wstp_autogen/mocs_compilation.o"
	@echo "... test_wstp_autogen/mocs_compilation.i"
	@echo "... test_wstp_autogen/mocs_compilation.s"
	@echo "... ueye_link_autogen/mocs_compilation.o"
	@echo "... ueye_link_autogen/mocs_compilation.i"
	@echo "... ueye_link_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

